[package]
name = "wowmulator"
version = "0.1.0"
authors = ["Juha Aarnio <juha.aarnio@live.fi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
